import Link from 'next/link';
import './globals.css';
import { Control } from './Control';

export const metadata = {
  title: 'Web tutorials',
  description: 'Generated by yoosb',
};

export default async function RootLayout({ children }) {
  const resp = await fetch('http://localhost:9999/topics', {
    cache: 'no-store',
  });
  const topics = await resp.json();

  return (
    <html>
      <body>
        <h1>
          <Link href='/'>Yoosb WEB</Link>
        </h1>
        <ol>
          {topics.map((topics) => {
            return (
              <li key={topics.id}>
                <Link href={`/read/${topics.id}`}>{topics.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
